### ISSUE TITLE
🚀 - Create utility `maskitoCaretGuard`

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/maskito#302]
### Which package(s) are relevant/related to the feature request?

@maskito/kit

### Description

New **optional** utility should listen `selectionchange` event.

**Use cases:**
* User can't move caret before `prefix`
* User can't move caret after `postfix`
* User can't move caret after `placeholder`

**⚠️  Be careful:**
* Firefox triggers `selectionchange` directly on `HTMLInputElement`, but other browsers emit it only on `Document`.
* SSR support!
* Shadom DOM support!

**Comment by waterplea** [comment]
**Observation:**
- `selectionchange` is triggered upon programmatic value change if element is focused (which is great)
- `selectionchange` works in Shadow DOM like in regular DOM
- `element.ownerDocument` allows us to get `document` in both SSR and Shadow DOM safely
- `selectionchange` is triggered on `document` so there's no way to get `target`

Since we only care about focused inputs and there can only be one at the moment, we can rely on a little utility from Taiga UI to tell if our input is focused inside `selectionchange` event callback:

```ts
export function tuiGetNativeFocused(doc: Document): Element | null {
    if (!doc.activeElement?.shadowRoot) {
        return doc.activeElement;
    }

    let element = doc.activeElement.shadowRoot.activeElement;

    while (element?.shadowRoot) {
        element = element.shadowRoot.activeElement;
    }

    return element;
}
```
